application: ebook-deals
version: 1
runtime: python
api_version: 1
 
inbound_services:
- mail

handlers:
- url: /stylesheets
  static_dir: stylesheets
  
- url: /images
  static_dir: static/images
  
- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico
  
- url: /tasks/_updatefeeds
  script: tasks/updatefeeds.py
#  login: admin
  
- url: /get_deals
  script: deals_json.py

- url: /deals
  script: deals_html.py
 
- url: /_ah/mail/manning@ebook-deals\.appspot\.com
  script: handle_incoming_manning.py
#  login: admin

- url: /_ah/mail/.+
  script: handle_incoming_others.py
#  login: admin 

- url: /.*
  script: deals_html.py
  

