runtime: python27
api_version: 1
threadsafe: false

# inbound_services:
# - mail

handlers:
- url: /stylesheets
  static_dir: stylesheets
  
- url: /images
  static_dir: static/images
  
- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico

- url: /_updatefeeds
  script: updatefeeds.py

- url: /get_deals
  script: deals_json.app

- url: /deals
  script: deals_html.app
 
- url: /.*
  script: deals_html.app
  
libraries:
- name: jinja2
  version: latest
